CREATE TABLE `companies` (
  `CompanyName` varchar(255) NOT NULL DEFAULT '',
  `CompanyNumber` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_CareOf` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_POBox` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_AddressLine1` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_AddressLine2` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_PostTown` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_County` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_Country` varchar(255) NOT NULL DEFAULT '',
  `RegAddress_PostCode` varchar(255) NOT NULL DEFAULT '',
  `CompanyCategory` varchar(255) NOT NULL DEFAULT '',
  `CompanyStatus` varchar(255) NOT NULL DEFAULT '',
  `CountryOfOrigin` varchar(255) NOT NULL DEFAULT '',
  `DissolutionDate` date DEFAULT NULL,
  `IncorporationDate` date DEFAULT NULL,
  `Accounts_AccountRefDay` int(10) DEFAULT NULL,
  `Accounts_AccountRefMonth` int(10) DEFAULT NULL,
  `Accounts_NextDueDate` date DEFAULT NULL,
  `Accounts_LastMadeUpDate` date DEFAULT NULL,
  `Accounts_AccountCategory` varchar(255) NOT NULL DEFAULT '',
  `Returns_NextDueDate` date DEFAULT NULL,
  `Returns_LastMadeUpDate` date DEFAULT NULL,
  `Mortgages_NumMortCharges` int(10) NOT NULL,
  `Mortgages_NumMortOutstanding` int(10) NOT NULL,
  `Mortgages_NumMortPartSatisfied` int(10) NOT NULL,
  `Mortgages_NumMortSatisfied` int(10) NOT NULL,
  `SICCode_SicText_1` varchar(255) NOT NULL DEFAULT '',
  `SICCode_SicText_2` varchar(255) NOT NULL DEFAULT '',
  `SICCode_SicText_3` varchar(255) NOT NULL DEFAULT '',
  `SICCode_SicText_4` varchar(255) NOT NULL DEFAULT '',
  `LimitedPartnerships_NumGenPartners` int(10) NOT NULL,
  `LimitedPartnerships_NumLimPartners` int(10) NOT NULL,
  `URI` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_1_CONDATE` date DEFAULT NULL,
  `PreviousName_1_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_2_CONDATE` date DEFAULT NULL,
  `PreviousName_2_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_3_CONDATE` date DEFAULT NULL,
  `PreviousName_3_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_4_CONDATE` date DEFAULT NULL,
  `PreviousName_4_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_5_CONDATE` date DEFAULT NULL,
  `PreviousName_5_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_6_CONDATE` date DEFAULT NULL,
  `PreviousName_6_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_7_CONDATE` date DEFAULT NULL,
  `PreviousName_7_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_8_CONDATE` date DEFAULT NULL,
  `PreviousName_8_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_9_CONDATE` date DEFAULT NULL,
  `PreviousName_9_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `PreviousName_10_CONDATE` date DEFAULT NULL,
  `PreviousName_10_CompanyName` varchar(255) NOT NULL DEFAULT '',
  `ConfStmtNextDueDate` date DEFAULT NULL,
  `ConfStmtLastMadeUpDate` date DEFAULT NULL,
  PRIMARY KEY (`CompanyNumber`),
  KEY `RegAddress_PostCode` (`RegAddress_PostCode`),
  KEY `RegAddress_PostTown` (`RegAddress_PostTown`),
  KEY `CompanyName` (`CompanyName`),
  KEY `Accounts_NextDueDate` (`Accounts_NextDueDate`),
  KEY `Accounts_LastMadeUpDate` (`Accounts_LastMadeUpDate`),
  KEY `ConfStmtNextDueDate` (`ConfStmtNextDueDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
